# Konfiguracja programatora
HARDWARE = usbasp
SLOWSCK = 1

# Konfiguracja sprzętu
MCU =attiny2313
F_CPU = 4000000

# Ustawienia fusebits i lockbits
LFUSE = 0xCE
HFUSE = 0xD9
#EFUSE = 0x00

#LOCK = 0x00

# Konfiguracja optymalizacji kodu
OPTIMIZE = s

# Konfiguracja kompilatora
PROG = main
OBJ = main.o
DEFS =
LIBS =
CC = @avr-gcc

include ../../inc/makefile-avr
