# Konfiguracja programatora
HARDWARE = usbasp
SLOWSCK = 1

# Konfiguracja sprzętu
MCU =atmega8
F_CPU = 10000000

# Ustawienia fusebits i lockbits
LFUSE = 0x0E
HFUSE = 0xC9
EFUSE = 0xFF

LOCK = 0x3F

# Konfiguracja optymalizacji kodu
OPTIMIZE = s

# Konfiguracja kompilatora
PROG = main
OBJ = main.o
DEFS =
LIBS =
CC = @avr-gcc

include ../../inc/makefile-avr
